docs/useTimeout.md
=> docs: fix module name typo

src/useRaf.ts
* Another animation frame will be requested before the cleanup function for `useEffect` is executed.
* Use `useLayoutEffect` to replace `useEffect`, in order to guarantee `cancelAnimationFrame` can work well.
More details can be found in issue https://github.com/streamich/react-use/issues/76
=> Fix synchronously re-render bug of useRef hook

src/useAsync.ts
Currently no arguments are passed into the memoized callback. This means the use of an async function that requires arguments isn't possible. For instance;
```
const fetchItems = async function(searchTerm) {
return (await fetch(`/api/items?q=${searchTerm}`)).json();
};
function Results({ searchTerm }) {
const { value } = useAsync(fetchItems, [searchTerm]);
// shows results
return (
<ul/> 
);
}
```
`searchTerm` in the `fetchItems` function will be `undefined`.
As stated in the `useCallback` [docs][1], the array of inputs as used on ln 24 is not passed as arguments, they must be passed when the memoized function is called.
> Note
> The array of inputs is not passed as arguments to the callback. Conceptually, though, that’s what they represent: every value referenced inside the callback …
=> Pass arguments to memoized callback in useAsync

package.json
According to React Blog, the newest version of React v16.7 doesn't include React Hooks, before they tag an extra version for upcoming hooks, we should lock the version to latest react 16.7.0 alpha version, rather than use `next` to specify its version info in `package.json`. More details can be found at https://reactjs.org/blog/2018/12/19/react-v-16-7.html#can-i-use-hooks-yet
=> Lock react and react-dom to a fixed version

docs/useKeyPress.md
Fixed a minor mistake in the `useKeyPress` docs (`keyboardjs` is an invalid option property).
=> docs(useKeyPress): renamed keyboardjs -> useKeyboardJS

src/useOrientation.ts
useOrientation breaks when device doesn't have orientation property in window.screen like iPhone.
=> fix useOrientation breaks in some devices

src/useSetState.ts
When we fetch data from server, use `setState(stateChangeObject)` in `useEffect` callback, the result is not correct.
See demo https://codesandbox.io/s/z6vn85pwpm. 
The reason is fetch data useEffect only execute once, it will not update when re-render. So [assign state](https://github.com/streamich/react-use/blob/master/src/useSetState.ts#L7) point the old state.
Do not use `setState(stateChangeObject)` but always use `setState(stateUpdaterFunction)`, refer to the old state can be avoided
=> fix: useSetState bug

docs/useKeyPressEvent.md, package.json, src/useKeyPressEvent.ts
This focuses on utilizing the onKeyup and/or onKeydown events unlike useKeyPress which involves state. useKeyPressEvent uses useKeyPress to achieve this functionality.
My needs were to fire an event on keyup and/or keydown, not just know whether it was pressed or not.
I am partial on the parameter implementation. I like named parameters when there are more than 2, especially when some are optional, but most custom hooks I have seen do not use objects. Let me know your thoughts on this. Also, as you'll see in the doc, this code sets a precedence on the keydown functionality (I assume this is used more), but maybe having named parameters would be better to easily do one or the other just as easily.
Lastly, I am automatically determining whether to use the useKeyboardJS param based on the …
=> Add useKeyPressEvent custom hook with associated doc

src/useMouse.ts
`element.offsetHeight` and `element.offsetWidth` will round the value to an integer.
`width` and `height` from `element.getBoundingClientRect()` is more precise.
=> feat: more precise size for useMouse

src/useGeolocation.ts
By default `tsc` was generating and object based on the initial state, where every property was always `null`.
This set `GeoLocationSensorState` the properties to their expected types, as well as defining the return type of `useGeolocation`.
=> fix: types for useGeolocation

.gitignore, package.json
Export the whole library in ES Module format as well so that bundlers like webpack, rollup and parcel can enable code splitting when `import { usexxx } from "react-use"`.
> currently only export in commonjs format
=> feat: emit code in ES Module format

src/useThrottle.ts
Fix as described here https://github.com/streamich/react-use/issues/154#issuecomment-477302736. I had to use `window.timeout` because of a type issue which I think is related to https://github.com/Microsoft/TypeScript/issues/842
Closes #154
=> fix: useThrottle discard intermediary calls

src/useAsync.ts, src/useAsyncRetry.ts
* fix deps args
* fix union type in useAsync and useAsyncRetry since https://github.com/streamich/react-use/pull/145/files#diff-8e6e0808e6745d8058a2f9cbd476172dR3
* remove useless useCallback in useAsyncRetry
* change setAttempt from value callback into function callback.
=> fix: fix deps arg and union type in useAsync and useAsyncRetry

src/__stories__/useFullscreen.story.tsx, src/useFullscreen.ts
The demo didn't use the `video` option. I added this in my first commit and got a TypeScript error:
```
Argument of type '{ onClose: () => void; video: null; }' is not assignable to parameter of type 'FullScreenOptions | undefined'.
Type '{ onClose: () => void; video: null; }' is not assignable to type 'FullScreenOptions'.
Types of property 'video' are incompatible.
Type 'null' is not assignable to type 'HTMLVideoElement | undefined'.
```
In the second commit the `video` option expects a video ref instead of a video element which makes this hook work without TypeScript errors. It's also more consistent to accept a ref in the options as the first parameter is already ref.
=> useFullscreen ref consistency

src/__stories__/useAsync.story.tsx, src/__stories__/useAsyncRetry.story.tsx, src/useAsync.ts, src/useAsyncRetry.ts
The dependency array is optional for `useEffect` so I think we should follow that pattern too. If `useEffect` doesn't have a dependency array it runs on every render. This doesn't seem like the behaviour you want would want from a hook like this so the best solution seems to make the default `deps` parameter an empty array.
=> Default dependency array for useAsync and useAsyncRetry

README.md, docs/useEffectOnce.md, src/__stories__/useEffectOnce.story.tsx, src/__stories__/util/ConsoleStory.tsx, src/index.ts, src/useEffectOnce.ts
A modified [`useEffect`](https://reactjs.org/docs/hooks-reference.html#useeffect) hook that only runs once. Similar to [useLifecycles](https://github.com/streamich/react-use/blob/master/docs/useLifecycles.md) but implementation can be used more similar to React's `useEffect`.
This implementation uses a ref to know if the effect already ran. I have seen a lot of people using this kind of implementation but I'm not sure if it's the best way. A more straightforward way would be:
```ts
import {useEffect, EffectCallback} from 'react';
const useEffectOnce = (effect: EffectCallback) => {
useEffect(effect, []);
}
export default useEffectOnce;
```
I thought I read somewhere that the ref implementation is preferable but I can't find it back.
=> useEffectOnce

docs/useMount.md, docs/useUnmount.md, src/__stories__/useMount.story.tsx, src/__stories__/useUnmount.story.tsx, src/useMount.ts, src/useUnmount.ts
Refactored `useMount` and `useUnmount` to reuse `useEffectOnce` as described in https://github.com/streamich/react-use/pull/196#issuecomment-478322228. Functionally the only difference is `useMount` can not have a clean-up routine.
I also added proper types and updated docs and stories
=> useMount and useUnmount refactor

docs/useLogger.md, src/__stories__/useLogger.story.tsx, src/useLogger.ts
Refactored `useLogger` to reuse `useEffectOnce` and `useUpdateEffect` instead of `useLifecycles`. You are also able to log multiple parameters now which can be handy if you want to log props and state which I tried to show in the updated story.
It would be nice if the hook could pick up the component displayName automatically but this does not seem possible: https://github.com/facebook/react/issues/15031.
=> useLogger refactor

README.md, docs/useDeepCompareEffect.md, package.json, src/__stories__/useDeepCompareEffect.story.tsx, src/index.ts, src/useDeepCompareEffect.ts, yarn.lock
A modified useEffect hook that is using deep comparison on its dependencies instead of reference equality. Using [`react-fast-compare`](https://github.com/FormidableLabs/react-fast-compare) as per recommendation.
I have "borrowed" dev warnings from https://github.com/kentcdodds/use-deep-compare-effect/blob/master/src/index.js. I wasn't sure if I had to use `process.env.NODE_ENV !== 'production'` or `process.env.NODE_ENV === 'development'` since I see both styles in this codebase.
Close #197
=> useDeepCompareEffect

docs/useCopyToClipboard.md, src/__stories__/useCopyToClipboard.story.tsx, src/useCopyToClipboard.ts
The current implementation assumes an asynchronous copy to clipboard function but uses [`copy-to-clipboard`](https://github.com/sudodoki/copy-to-clipboard) by default which is synchronous. `copy-to-clipboard` also [returns a boolean](https://github.com/sudodoki/copy-to-clipboard#api) if additional user interaction was needed as a prompt modal is presented in browsers that don't support `execCommand`. This value is not accessible in the current version. 2 examples why the hook itself has to determine how text is copied to the clipboard as I have pointed out in https://github.com/streamich/react-use/issues/208#issuecomment-480472083.
After playing around with it a little bit more I came to the conclusion that it might be a bad pattern to have callbacks in the parameters of a hook. I changed …
=> Improved useCopyToClipboard

package.json, yarn.lock
yarn start wasn't working as (i think) babel-loader wasn't being installed as a peer dependency of existing babel 6? so added babel-loader directly
Also, as babel presets were at >v7 and are also part of the @babel scope, thought it'd be best to upgrade babel to v7 using the same scope.
Now yarn start works as expected and the new test still works
=> Upgrade babel core and add babel loader for storybook

docs/useGeolocation.md, src/useGeolocation.ts
This PR adds ability to pass [position options](https://developer.mozilla.org/docs/Web/API/PositionOptions) for `useGeolocation` hook.
=> Add ability to pass position options to useGeolocation

src/useRefMounted.ts
Not sure if this is intentional or not but theres no need for this to rerun on every render? Tho I suppose its not really an issue.
> If you want to run an effect and clean it up only once (on mount and unmount), you can pass an empty array ([]) as a second argument.
[Tip: Optimizing Performance by Skipping Effects](https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects)
=> fix(useRefMounted): only run and cleanup once

README.md, docs/usePrevious.md, src/__stories__/usePrevious.story.tsx, src/__tests__/usePrevious.test.tsx, src/index.ts, src/usePrevious.ts
React state hook that returns the previous state as described in the [React hooks FAQ](https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state).
=> usePrevious

docs/useToggle.md, src/__stories__/useToggle.story.tsx, src/__tests__/useToggle.test.tsx, src/useToggle.ts
Ignore non-boolean values parameters  of `useToggle` updater function and toggle state as if there was no parameter. This allows you to use the update action like `onClick={toggle}`.
Fixes #278
=> usetoggle no param casting

src/useAsyncFn.ts
Passing arguments to `useAsyncFn` fetcher might be very useful, for example in case of autocomplete:
```jsx
const [state, fetchSuggestions] = useAsyncFn(query => { /* fetch result somehow */ });
<Autocomplete onLoad={fetchSuggestions} items={state.value} />
```
=> Pass arguments to useAsyncFn fetcher

src/useMap.ts
The type of useMap is too simplistic.
```typescript
const [state1, setState1] = useMap<{ [key: string]: boolean }>();
setState1.get('test');      // the `get` method will return `any`
setState1.set('test', 123); // type of 123 is number, but there not error
const [state2, setState2] = useMap({
abc: 123,
bcd: '456',
cde: {
test: 123,
},
});
// all method under there are legal
setState2.get('test');
setState2.get('bcd');
setState2.get('cde');
setState2.set('abc', '123');
setState2.set('bcd', 123);
setState2.set('test', 78);
setState2.remove('abcdefg');
```
```typescript
const [state1, setState1] = useMap<{ [key: string]: boolean }>();
setState1.get('test');      // the `get` method will return `boolean`
setState1.set('test', 123); // throw a error, `123` is not boolean
const [state2, …
```
=> fix(useMap): more stringent type

src/util/createHTMLMediaHook.ts
Given: `useAudio` which is playing and `autoPlay: false` (default)
When: `src` changes
Then expected: Audio stops playing and `state.isPlaying` changes to `false`
Then actual: Audio stops playing, but `state.isPlaying` remains `true`
This PR fixes this. The issue is that `onPause` doesn't fire when `src` changes even though playback is stopped.
Affected browsers: Chrome, Firefox and maybe others
=> fix(useAudio): src change should reset isPlaying state

src/useSetState.ts
I'm not a TS guru by any means, but I found it odd that the callback type 1.) didn't accept a `prevState`, nor return a _partial_ of `prevState`.
Updating this type seems to fix the issue for me.
=> Fix useSetState callback parameter type

src/__stories__/util/ShowDocs.tsx
Markdown files don't render properly in Storybook. I'm not sure what broke it so not sure if this is the best fix
=> fix: fix Storybook docs Markdown import

README.md, docs/createReducer.md, src/__stories__/createReducer.story.tsx
=> createReducer docs

src/useLocalStorage.ts
just a quality of life change, any time the state changes, then the local storage should be updated, not on every render.
=> fix: save to localStorage only when state changes

src/useList.ts, src/useMap.ts
I only explored this route as I was seeing useMap not update object state correctly when using `...map`. IE the state was getting overwritten always with the new field only. 
I don't know why this was happening in some circumstances and not in others, but this makes it work in both environments.
=> useMap uses previous map state upon set and remove

src/useSize.tsx
Fixes error in useSize: Cannot read property 'contentWindow' of null
ref #442
=> fix(useSize): prevents accessing iframe's property when it's not defined

README.md, docs/useIsomorphicLayoutEffect.md, src/__stories__/useIsomorphicLayoutEffect.story.tsx, src/index.ts, src/useIsomorphicLayoutEffect.ts
=> Export useIsomorphicLayoutEffect + docs

src/useMedia.ts
Initializing state with result from call to window.matchMedia avoids possible initial flicker of returned value, when media query matched initially
=> useMedia - initialize state with call to media query

docs/Usage.md, docs/useEvent.md, docs/useFullscreen.md, docs/useInterval.md, docs/useKey.md, docs/useKeyPress.md, docs/useKeyPressEvent.md, docs/useKeyboardJs.md, docs/useSpring.md, docs/useStartTyping.md, package.json, src/index.ts
Fixes #384 #183 
I've unified docs to show ES6 import. I can revert that if you want to keep it like that for some reason.
=> Remove peer deps from index export

src/useMouse.ts, src/useMouseHovered.ts
=> fix: useMouse & useMouseHovered type definitions for SVG

package.json
I believe `opencollective-postinstall` must be a prod dependency otherwise `postinstall` would fail unless it's installed globally or maybe another package installed it? Also `|| true` throws an error on Windows.
=> bug: fix opencollective postinstall error

src/useWindowScroll.ts
> For cross-browser compatibility, use window.pageYOffset instead of window.scrollY.
(https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY)
=> feat: useWindowScroll - for cross-browser compatibility

.editorconfig
.editorconfig confliced with tslint and made development pretty hard (due to a lot of lint warnings)
Now they're working in harmony😌
=> .editorconfig synchronised with tslint.json

src/useMouse.ts
Replace `window.scrollX` with `window.pageXOffset` and the equivalent for the Y coordinate in `useMouse`
These are aliases but with better browser support (including IE), see here: https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset 
This should fix #524
=> fix support IE in useMouse

README.md, docs/useCounter.md, src/__stories__/useCounter.story.tsx, src/__tests__/useCounter.test.ts, src/useCounter.ts
Implemented #273;
Added runtime type checks;
Tests for all that stuff;
Docs;
=> feat: add min/max to useNumber

src/useAsyncFn.ts, src/useCopyToClipboard.ts, src/useDrop.ts, src/useDropArea.ts, src/useMountedState.ts, src/usePromise.ts
- Improved useMountedState (now returns only one function instead a new one each call);
- Replaced all `useRefMounted` to `useMountedState` to deprecate first one in later releases;
=> refactor: use useMountedState instead of useRefMounted

package.json, yarn.lock
Made a `npx yarn-deduplicate` so now `yarn.lock` has no mistakes.
Before this commit there was a mismatch in @types/react versions which lead to `tsc` fail.
Furthermore it became much faster to install.
=> Dedupe yarn.lock

docs/useUpsert.md, src/__stories__/useUpsert.story.tsx, src/__tests__/useUpsert.test.ts, src/index.ts, src/useUpsert.ts
This PR adds the `useUpsert` hook.
`useUpsert` provides a superset of `useList`, with the additional method `upsert`, which combines update or insert functionality. `useUpsert` requires that a comparison function is passed when initialising the hook.
Looking forward to your feedback!
=> feat: useUpsert

src/__tests__/useAsync.test.tsx, src/__tests__/useAsyncFn.test.tsx
useAsync tests been missing render await in `onBefore` stage;
useAsyncFn tests been missing `act` calls;
=> fix: async test warnings

package.json, src/__tests__/useRafLoop.test.tsx, yarn.lock
Fix: #546;
Fix useRafLoop tests. Now it always succeed.
Added `raf-stub` package to test RAF dependant hooks predictably.
=> fix: succeed useRafLoop tests

README.md, docs/useTimeoutFn.md, src/__stories__/useTimeoutFn.story.tsx, src/__tests__/useTimeoutFn.test.ts, src/index.ts, src/useTimeoutFn.ts
Hook giving ability to run function after timeout without re-rendering parent component.
Giving handles to check the call state and cancel the timeout.
Timeout restarts itself on deps change and unmout.
=> feat: useTimeoutFn

src/useTimeoutFn.ts
Similar to the `clearTimeout`, the `setTimeout` shouldn't need the `window` object.
As a result this function can work in node environment, e.g. SSR.
=> Removed prepended window from setTimeout

src/__tests__/useSetState.test.ts, src/useSetState.ts
Addresses https://github.com/streamich/react-use/issues/555 
Wraps the callback from `useSetState` in `useCallback` to memoize it so that folks following the Best Practices from the [React FAQ](https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies) with the `react-hooks/exhaustive-deps` [rule](https://www.npmjs.com/package/eslint-plugin-react-hooks) enabled don't trigger endless rerenders in a `useEffect(() => {}, [setState]);` where `setState` is constantly changing out from under them.
I tried to write a couple tests for this but I'm not really sure what angle to approach it from or how to layer everything together to test for something useful.
```js
const myComponent = () => {
const [{ loading, data }, setState] = useSetState({ loading: …
```
=> fix(useSetState): memoize setState callback

docs/usePreviousDistinct.md, src/__stories__/usePreviousDistinct.story.tsx, src/__tests__/usePreviousDistinct.test.tsx, src/index.ts, src/usePreviousDistinct.ts
=> feat: add usePreviousDistinct

src/__tests__/useEffectOnce.test.ts, src/__tests__/useMount.test.ts, src/__tests__/useUnmount.test.ts
First bunch of tests for lifecycle hooks blocks. It includes tests for:
- useMount
- useUnmount
- useEffectOnce
=> First bunch of tests for lifecycle hooks blocks

src/__tests__/useWindowSize.test.tsx, src/useWindowSize.ts
Use [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) to improve performance of resize handler. Currently tests are failing though so it would be nice if someone could point me in the right direction on how to mock requestAnimationFrame 🙂
=> Improve useWindowSize performance with requestAnimationFrame

src/__tests__/useMap.test.ts, src/useMap.ts
Hey guys,
Here is my proposal following the issue https://github.com/streamich/react-use/issues/456
All feedbacks are more than welcome
Cheers
=> Memoized utils methods for useMap

src/useDebounce.ts
Removed hook dependencies from function arguments to align hook API with standard React hooks. The dependency array was also passed as single array and spread the items in the array as arguments which probably resulted in no developers using arguments of the timeout function.
I have also rename `args` to `deps` for consistency.
Closes #618
=> useDebounce remove deps from function arguments

package.json, src/useFullscreen.ts, yarn.lock
This updates the dependency and the code for `useFullscreen()` to be compatible with `screenfull` v5.0.0.
#598 is broken because it doesn't fix the code.
=> Update screenfull to v5.0.0

docs/useList.md, src/__stories__/useList.story.tsx, src/__tests__/useList.test.ts, src/useList.ts
`useMap` has a `reset` callback that resets the state to its initial value which I was missing in `useList` so I added it here. I also added tests and updated the docs and story.
I also added memoization of the callback utils and aded tests for this.
Last but not least I was thinking about removing `clear` because you mostly need to be able to clear the array when you're starting with an empty array in the first place. The `reset` callback proposed here results in the same behaviour as it resets to the initial (default) value `[]`. I haven't implemented it as I wanted to know what others think
=> Add reset util to useList

package.json
More info on why and how in #661
=> fix: move @types/react-wait to dependencies, closes #661

src/useFullscreen.ts, src/useMouse.ts, src/useScroll.ts, src/useScrolling.ts
It doesn't make sense to add `ref.current` to a dependency array, see https://github.com/facebook/react/issues/16121#issuecomment-511369830
Related #638
=> Remove ref.current from dependency lists

README.md, docs/useIntersection.md, package.json, src/__stories__/useIntersection.story.tsx, src/__tests__/useIntersection.test.tsx, src/index.ts, src/useIntersection.ts, yarn.lock
As described in https://github.com/streamich/react-use/issues/604.
=> Implement useIntersection hook.

src/__tests__/useList.test.ts, src/useList.ts
Update `useList`'s push to behave like [Array.prototype.push()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) to allow pushing multiple items in one go.
=> useList allow pushing multiple items

CONTRIBUTING.md, package.json
To encourage contributors to write tests for existing hooks I've added a section about code coverage
=> Added code coverage script + document in contributing guidelines

README.md, docs/useRafState.md, src/__stories__/useRafState.story.tsx, src/__tests__/useRafState.test.ts, src/index.ts, src/useMouse.ts, src/useRafState.ts, src/useScroll.ts, src/useWindowScroll.ts, src/useWindowSize.ts
`useState` hook that only updates state after `requestAnimationFrame`. Can be reused in existing hooks in this library. Has the same signature as React's `useState`.
=> feat: useRafState

README.md, docs/useMultiStateValidator.md, src/__stories__/useMultiStateValidator.story.tsx, src/__tests__/useMultiStateValidator.ts, src/index.ts, src/useMultiStateValidator.ts
Acts much like the `useStateValidator` but this time it handles multiple states simultaneously.
Below validator will turn to true only if both values are even
```js
const [state1, setState1] = React.useState(1);
const [state2, setState2] = React.useState(1);
const [[isValid]] = useMultiStateValidator([state1, state2], s => [s.every(num => !(num % 2))]);
```
=> feat: useMultiStateValidator

src/useSize.tsx
`window.removeEventListener` could be null for a **removed** iframe element in **Safari 11** while `window` is regarded as a reference to `iframe.contentWindow`.
=> fix: useSize avoid crash in Safari 11

src/__tests__/resolveHookState.ts, src/__tests__/useCounter.test.ts, src/useCounter.ts, src/useGetSet.ts, src/util/resolveHookState.ts
As it is done in React's `setState` this function receives new state as 1st parameter, it will be returned as-is if not a function and invoked otherwise receiving the 2nd parameter as a current state value like it is in react's implementation.
It will be very useful for stateful hooks to make the seamless usage comparing to react's hooks.
I have plans to move all the hooks to this implementation.
=> feat: react-like state resolver

src/__tests__/useStateList.test.ts, src/__tests__/useWindowSize.test.tsx, src/createReducer.ts, src/useStateList.ts, src/useWindowSize.ts, src/util/parseTimeRanges.ts
On previous version hook has several problems:
- Attempt to call `next()`/`prev()` on unmounted component caused errors.
- Consequal `next()`/`prev()` call withon a single render tic been causing only +/- 1 state step. 4ex: next test case would vail on previous implemntation. 
```javascript
const hook = renderHook( () => useStateList(['a', 'b', 'c']) );
expect(hook.result.current.state).toBe('a');
act(() => {
hook.result.current.next();
hook.result.current.next();
hook.result.current.next();
});
expect(hook.result.current.state).toBe('a');
```
=> fix(useStateList): rework the hook

src/__tests__/useEvent.test.ts, src/useEvent.ts
The arguments of useEvent, name, handler, options are weak type now. 
```
const useEvent = (
name: string,
handler?: null | undefined | ((event?: any) => void),
target: null | UseEventTarget = defaultTarget,
options?: any
) => 
```
But name and handler, options can be infered from target. So I improved the type of useEvent arguments.
This makes happy coding when using useEvent() name and handler, options.
Also I added a test for useEvent.ts.
=> improve useEvent type

docs/useStateList.md, src/__stories__/useStateList.story.tsx, src/__tests__/useStateList.test.ts, src/useStateList.ts
Implemented `currentIndex`, `setState`, `setStateAt` methods as requested in #634;
Reworked a bit implementation of `next` and `prev` to make it reuse the `setStateAt` method;
=> feat(useStateList): add `currentIndex`, `setState`, `setStateAt` methods

src/useLocation.ts
IE does not have window.Event constructor.
=> fix: 🐛 check window.Event constructor exists in useLocation

src/useThrottleFn.ts
The typing of `useThrottleFn(fn, ms, args)` does not make sure that the type of `args` matches the type of the arguments of `fn`.
This may lead to runtime issues, for example with the following code:
```tsx
import React, { FC } from 'react';
import { useThrottleFn } from 'react-use';
interface Rect {
size: {
width: number;
height: number;
};
color: string;
}
const area = (rect: Rect): number => rect.size.width * rect.size.height;
const Test: FC<{ foo: string }> = ({ foo }): JSX.Element => {
const bar = useThrottleFn(area, 200, [foo]);
return <div>{bar}</div>;
};
export default Test;
```
The above will crash at runtime, since `foo` (a `string`) is passed to `area` instead of a `Rect`:
After this PR, the type is properly checked, and typing errors are raised appropriately:
=> Improve useThrottleFn type definition

src/useAsyncFn.ts, tests/useAsyncFn.test.tsx
The current implementation of `useAsyncFn` can cause race conditions between two Promises whenever the callback is called twice in a row as it never discard previous queries. The latest query is considered to be the results.
As consequence, we can leverage this bug in `useAsync` with this scenario:
- `<UserProfile userId={1} />` rendered - initial render
- `<UserProfile userId={2} />` rendered - props updated
- Query for userId=2 succeeds - we see the profile of 2
- Query for userId=1 succeeds - we replace the profile of 2 by the one of 1 while userId=2
```
function UserProfile({ userId }) {
const {value} = useAsync(async () => await fetchUserInfo(userId));
return <>{value}</>;
}
```
=> fix: useAsyncFn does not discard old promises and might produce races

src/useUnmount.ts, tests/useUnmount.test.ts
Fix: #792 
Previous hook version stored the first callback version and invoked only that version.
=> fix(#792): make useUnmount invoke the recent callback version

README.md, docs/useFirstMountState.md, docs/useRendersCount.md, src/__stories__/useFirstMountState.story.tsx, src/__stories__/useRendersCount.story.tsx, src/index.ts, src/useFirstMountState.ts, src/usePreviousDistinct.ts, src/useRendersCount.ts, src/useUpdateEffect.ts, tests/useFirstMountState.test.ts, tests/useRendersCount.test.ts
feat(useFirstMountState): hook to track if render is first;
feat(useRendersCount): hook to track renders count;
feat(useUpdateEffect): refactored with useFirstMountState hook;
feat(usePreviousDistinct): refactored with useFirstMountState hook;
=> feat: add useFirstMountState & useRendersCount hooks

src/useUpdate.ts
useUpdate hook can hit maxInt, failing to trigger rerender as the value we pass must always be different
=> fix: useUpdate hitting maxInt, failing to trigger rerender

README.md, docs/useUnmountPromise.md, src/index.ts, src/useUnmountPromise.ts, tests/useUnmountPromise.test.ts
Another way to check if component is still mounted.
- ~~[ ] Add hook's story at Storybook~~
=> feat: 🎸 add useUnmountPromise hook

README.md, docs/useScrollbarWidth.md, package.json, src/__stories__/useScrollbarWidth.story.tsx, src/index.ts, src/useScrollbarWidth.ts, tests/useScrollbarWidth.test.ts, yarn.lock
This hook uses [@xobotyi/scrollbar-width](https://github.com/xobotyi/scrollbar-width) underneath, which is well tested and grown from my scrollbars component.
This PR absorbs #653
=> feat: useScrollbarWidth hook;

src/useMap.ts, tests/useMap.test.ts
Fixes #816 
Due a change in `useMap` fixing the `get` method using an outdated closure an error was introduced where the methods with side effects, i.e. `set`, `remove` and `reset` were no longer memoized properly and therefore not stable across renders. 
This PR memoizes the individual methods with side effects properly but *not* the entire `utils` object.
=> fix(useMap): methods with side effects should be stable across renders.

src/useSet.ts, tests/useSet.test.ts
Fixes #808 
I took the liberty to create a PR for this bug as well as it is basically similar to #816 which was fixed in PRs #817 and #826
=> fix(useSet): "has" method in useSet updated to reference latest set object

README.md, docs/useCustomCompareEffect.md, docs/useShallowCompareEffect.md, package.json, src/index.ts, src/useCustomCompareEffect.ts, src/useDeepCompareEffect.ts, src/useShallowCompareEffect.ts, stories/useCustomCompareEffect.story.tsx, stories/useShallowCompareEffect.story.tsx, tests/useCustomCompareEffect.test.ts, tests/useShallowCompareEffect.test.ts, yarn.lock
This pr adds 2 new hooks in addition to useDeepCompareEffect: 
* useShallowCompareEffect Hook
* useCustomCompareEffect Hook
Here is a use case which I bumped in, where I found useShallowCompareEffect useful: 
```
const Comp1 = (props) => {
const { opt1, opt2, ...otherOptions } = props.options;
useShallowCompareEffect(() => {
dataService(otherOptions);
}, [otherOptions])
.....
}
```
In this case we want to call `dataService` only if something inside `otherOptions` has changed. As spread operator was used to create `otherOptions` object, reference to it is different on each rerender, so we can't use regular `useEffect` in this case.
I also added `useCustomCompareEffect` which allows to provide custom compare callback for more specific use cases.
*`except inside dev mode code paths`
=> feat: useShallowCompareEffect and useCustomCompareEffect

docs/useLocalStorage.md, src/useLocalStorage.ts, stories/useLocalStorage.story.tsx
Implemented `remove` method as requested in #229 ;
Reworked a bit implementation of the initialization of useState to make sure not to invoke `localStorage.setItem()` when localStorage.getItem(key) is null && InitialValue is undefined;
=> feat(useLocalStorage): add remove method. (#229)

src/useUpdateEffect.ts, tests/useUpdateEffect.test.ts
Fixes #863 
`useUpdateEffect` does not return the result of the `effect` passed, this results in cleanup function never being called on unmount. This PR fixes it by making `useUpdateEffect` return the result of the passed effect.
=> fix: useUpdateEffect returns optional cleanup function

tests/useUpdateEffect.test.ts
The test of my previous PR #864 is wrongly successful, I was testing that the effect was called, not the cleanup! This PR fixes it by testing that the cleanup effect was called on unmount, not the effect.
=> fix: useUpdateEffect test returning false positive

src/useCustomCompareEffect.ts
Added generic to useCustomCompareEffect for dependencies inference in compare function
Using useCustomCompareEffect ran into the inconvenience of having no type inference in the compare function.
=> feat: Dependencies inference for useCustomCompareEffect

src/useTitle.ts, tests/useTitle.test.ts
Restore the previous title when the current component is destroyed.
=> Modify useTitle.ts' logic

src/useCopyToClipboard.ts, tests/useCopyToClipboard.test.ts
Refactoring `useCopyToClipboard` to prevent invalid values to be passed to `copy-to-clipboard` helper. This prevent the helper from launching prompts and other weird behavior, also allows us to have a more relevant state, given the fact that the prompts seem to not copy anything to clipboard, see #898
=> refactor: use copy to clipboard

docs/useMap.md, src/useMap.ts, tests/useMap.test.ts
`useMap`: Add `setAll` to allow providing entirely new object
=> feat: `useMap`: allow resetting with provided value other then initial

src/useIntersection.ts, tests/useIntersection.test.tsx
fix(useIntersection): return null if IntersectionObserver is not supported
fix(useIntersection): reset an intersectionObserverEntry when the ref changes
fix(useIntersection): disconnect an old IntersectionObserver instance when the ref changes
=> fix(useIntersection): some bugs

stories/useError.story.tsx
Fixed link to useError.md
the [Storybook docs-page for `useError`](https://streamich.github.io/react-use/?path=/story/side-effects-useerror--docs) currently shows the docs for useLocalStorage. This fixes that.
=> Fixed link to useError.md

docs/useCustomCompareEffect.md
This PR makes `useCustomCompareEffect` example on docs properly import itself (instead of importing `useDeepCompareEffect`)
=> docs: useCustomCompareEffect should import itself

src/useMediaDevices.ts, src/util.ts
Fix: [useMediaDevices(): TypeError: Cannot read property 'addEventListener' of undefined](https://github.com/streamich/react-use/issues/820)
- [-] Comment the code, particularly in hard-to-understand areas
- [-] Add documentation
- [-] Add hook's story at Storybook
- [-] Cover changes with tests
- [-] Provide 100% tests coverage
- [-] Make sure types are fine (`yarn lint:types`).
=> fix: handle undefined mediaDevices

docs/useAsyncFn.md, src/useAsyncFn.ts, tests/useAsyncFn.test.tsx
`useAsyncFn` - keeping the previous state when start running the async function [#934]
=> useAsyncFn: keeping the previous state when start running the async function

docs/useBeforeUnload.md, src/useBeforeUnload.ts, stories/useBeforeUnload.story.tsx
Allow passing a function as dirty flag to `useBeforeUnload` hook.
Link documentation of an example how to use this with fast-changing dirty functions.
Closes #842
=> feat(useBeforeUnload): allow passing a dirty function (#842)

README.md, docs/useMethods.md, src/index.ts, src/useMethods.ts, stories/useMethods.story.tsx, tests/useMethods.test.ts
=> feat: add useMethods state hook

src/useHoverDirty.ts
Fixes `/* eslint-disable */ for `useHoverDirty` per https://github.com/streamich/react-use/issues/947
=> fix: useHoverDirty eslint fix

docs/useSet.md, src/useSet.ts, stories/useSet.story.tsx, tests/useSet.test.ts
This adds a `toggle` method to the `useSet` hook. It creates a handy wrapper on top of `add` and `remove`.
=> feat(useSet): add toggle a method

src/useToggle.ts
This refactor to the useToggle hook switch the internal logic to a single useReducer instead of the useState and useCallback hooks, since the dispatch function will have the same reference on every rerender, removing the need to implemente a memoized function.
=> Refactor (useToggle): useReducer optimization and less hooks usage

src/useMeasure.ts
When upgrading to v15, I discovered some issues with `useMeasure` forcing me to downgrade to v14. Hopefully these changes fixes those issues...
* It was no longer possible to define the ref type, meaning components requiring a certain type of ref would reject it. Fixed this by making the function generic again.
* Previously you _had to_ define the ref type, while in v15 you _couldn't_. Fixed this by giving the generic type a default type of `HTMLElement`.
* The implicit typing of `useMeasureMock` combined with the ternary default export statement made the imported type of `useMeasure` very messy. Fixed this by making the type of `useMeasureMock` explicitly match `useMeasure`.
=> fix: 🐛 correct useMeasure typings

src/createGlobalState.ts, src/useCss.ts, src/useFullscreen.ts, src/useRaf.ts, src/useStartTyping.ts
Uses `useIsomorphicLayoutEffect` everywhere instead of `useLayoutEffect`. This should remove React warnings on server.
=> fix: 🐛 use useIsomorphicLayoutEffect everywhere

src/useKeyboardJs.ts
Fixed the importing of the KeyboardJS library with backward compatibility. Updated how bindings are set to prevent KeyboardJS from calling handlers repeatedly while holding keys.
=> fix: repair useKeyboardJs hook

stories/useKeyPressEvent.story.tsx
Reported at: https://github.com/streamich/react-use/issues/1131
At https://streamich.github.io/react-use/?path=/story/sensors-usekeypressevent--demo
When we try to decrement the count by pressing [ key. It decrements the count by two, instead of one.
Fix: Removed the extra decrement call.
=> fix: Demo: useKeyPressEvent is decrementing ('[') twice

src/usePrevious.ts
Better to use two-variables exchange than `useEffect` with new
function on each render.
=> feat(usePrevious): reworked the hook, now it is more memory-efficient.

src/createReducerContext.ts, src/createStateContext.ts
`createFactory` is deprecated in React 16.13.0. I replaced it with calls to `createElement`. Fixes #1035.
=> fix: replace createFactory usages with createElement

tests/useCopyToClipboard.test.ts
For reference: https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines
=> [Fix] common misspelling errors

docs/useMount.md, docs/useUnmount.md
Reading the documentation, I think the `useLifecycles` hook fits better on both situations.
Documentation for both:
useLifecycles — calls mount and unmount callbacks.
useEffectOnce — a modified useEffect hook that only runs once.
=> fix (documentation): Rename useEffectOnce to useLifecycles on documentation example

README.md
The `useMouseWheel` docs in the README was incorrectly pointing to `useMouse`. This fixes that.
=> Fixed `useMouseWheel` README link

tests/useIntersection.test.tsx, tests/useSearchParam.test.ts
Typescript doesn't like that you're deleting properties that might be undefined in your tests.
is is set the types to `any`.
=> fix: Fix issues in tests

src/useGeolocation.ts
Typescript 4.1 has `PositionError` renamed to `GeolocationPositionError` and it caused errors
=> fix: #1646

src/misc/util.ts, src/useUpdate.ts, tests/useUpdate.test.ts
=> chore(useUpdate): improve `useUpdate` test suite

src/useMeasure.ts
Type of `[noop, defaultState]` is :
```
Array<(
| Pick<DOMRectReadOnly, "x" | "y" | "top" | "left" | "right" | "bottom" | "height" | "width"> 
| (() => void)
)>
```
This fix it.
=> fix: proper definition for `useMeasure`

src/useMountedState.ts
useEffect when deps is not provided, It will be executed in the three life cycles of componentDidMount, componentDidUpdate, componentWillUnmount.
useMountedState should change state only in componentDidMount, componentWillUnmount.
=> fix: useMountedState should not change state on componentDidUpdate lifecycle

docs/createGlobalState.md, src/factory/createGlobalState.ts, tests/createGlobalState.test.ts
This PR makes the `createGlobalState` function compatible with the React API. This means 2 things:
- It allows using a function in setState, as in `setState(prevState => prevState + 1)`
- It allows using a function in the initial state, as in `createGlobalState(() => 0)`
Also, as a side effect:
- It improves the types when the initial value is passed or set as the generic argument, while relying on the React original type for the return (`SetStateAction`).
- It fixes the current tests that were using an incorrect syntax and extends them to the new use cases and types.
- Extends docs and fixes a minor grammar issue.
We mobbed this in our team at Spotify.
=> Makes createGlobalState API compatible with React's useState API

src/useOrientation.ts, tests/useOrientation.test.ts
When using useOrientation in an SSR app it causes the error window is undefined to be thrown.
I took over from #1569
Fixes #1570
also noticed that `useOrientation` is listed here #947, but no `eslint-disable` in the file.
=> Fix useOrientation on SSR

src/useMeasure.ts
Re-applied the changes of @thevtm from https://github.com/streamich/react-use/pull/479 to the `useMeasure` hook, because the Resize Observer API [also works](https://github.com/WICG/resize-observer/issues/9#issuecomment-228181533) on SVG elements.
@streamich can you have a look?
=> fix: useMeasure type definitions for SVG

src/useWindowScroll.ts, tests/useWindowScroll.test.tsx
useWindowScroll may lose window scroll change at mount (see bug #1699)
We have to update window scroll at mount, before subscription.
Window scroll may be changed between render and effect handler.
Also, we can use lazy initial value for state (to prevent scroll position recalculation at each render).
It is legal, see there: https://kentcdodds.com/blog/use-state-lazy-initialization-and-function-updates
=> fix for useWindowScroll may lose window scroll change at mount #1699

src/useStateWithHistory.ts, tests/useStateWithHistory.test.ts
Make `useStateWithHistory` support the callback style set state, e.g. `setState(current => current + 1)`. 
Currently, it's typed as if it does support it, but the `current` parameter is always `undefined`.
Fixes #1916
=> fix(useStateWithHistory): support callback style setState

src/useSetState.ts
Because [here](https://reactjs.org/docs/hooks-reference.html#usestate).
=> `setState` is unnecessary in deps

docs/useAsyncFn.md
When trying to test the `useAsyncFn` example, an error occurs: `Error: Maximum call stack size exceeded`.
Reproduction link: https://codesandbox.io/s/eager-christian-2q5iu?file=/src/App.js (click on _Start loading_ to see the error).
Fix : rename `fetch` to avoid conflict with `window.fetch`.
=> docs: Fix useAsyncFn example to avoid error

src/factory/createBreakpoint.ts
Fixes #1493 
I tried to write tests for this but I couldn't manage with the setup `react-use` has. I think it's hard to catch in JSDom.
=> Default to window.innerWidth instead of 0 in createBreakpoint

src/factory/createHTMLMediaHook.ts, src/useAudio.ts, src/useVideo.ts
this commit fix #969 
useAudio and useVideo hooks are using createHTMLMediaHook.
I added a generic parameter to createHTMLMediaHook
I also enhanced typing of some other variables inside createHTMLMediaHook.
Now we can use `as const` in return and there is no need to createHTMLMediaHookReturn.
=> fix: add generic parameter to createHTMLMediaHook. no typecheck problem with ref anymore

src/useLocalStorage.ts, tests/useLocalStorage.test.ts
Currently if you update the `key` prop of a `useLocalStorage` hook instance, it won't read again the local storage. So it will write the previous state to a new local storage key without initially read it. This PR forces the hook to read again local storage and update its state accordingly when the `key` prop changes. 
Fixes #1147
=> fix(useLocalStorage): reinitialize on key change

tests/useEnsuredForwardedRef.test.tsx
This only adds a test for `ensuredForwardRef`
```diff
-  useEnsuredForwardedRef.ts    |      75 |      100 |      50 |      75 | 31-33
+  useEnsuredForwardedRef.ts    |     100 |      100 |     100 |     100 |
```
=> test: Add test coverage for ensuredForwardRef

docs/useAudio.md, src/factory/createHTMLMediaHook.ts, tests/useAudio.test.ts
At present, useAudio cannot get whether it is playing in a weak network environment
Difficult to test in a weak network environment
=> feat: useAudio add playing state

docs/useMedia.md, src/useMedia.ts, tests/useMedia.test.ts
Fix server side render hydration mismatch when a default value is provided to useMedia
Before, in pr #464 when server side rendering a component that used useMedia, the server's initial state would initialize to false, but then when React hydrated this on the client, it would initialize to the result of the media query. This caused bug #1885 because When React hydrates the server render, it may not match the client's state. The [React docs](https://reactjs.org/docs/react-dom.html#hydrate) have a little more info on why this can lead to perf issues as well.
=> fix: useMedia SSR hydration bug with defaultState

src/factory/createReducerContext.ts, src/factory/createStateContext.ts, src/useMedia.ts, stories/useHarmonicIntervalFn.story.tsx, stories/useMouse.story.tsx, stories/useMouseHovered.story.tsx, stories/useMouseWheel.story.tsx, tests/createReducerContext.test.tsx, tests/createStateContext.test.tsx
In @types/react@18 children was removed from FC type.
I get type errors in `createReducerContext`, `createStateContext`
Changes of this PR are compatible with 17 and 18 typings versions.
Detail in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210
=> fix: resolve @types/react@18 break change, React.FC

src/useMedia.ts, tests/useMedia.test.ts
As of our, `useMedia` hook uses [addListener](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener) which is deprecated. This PR simply updates the current hook to the recommended approach from MDN :)
=> fix: update useMedia hook to use recommended approach of MDN

docs/useSet.md, src/useSet.ts, stories/useSet.story.tsx, tests/useSet.test.ts
In using useSet, we decided that we needed a method that could erase all values.
We have also added text to the documentation regarding the behavior of the reset method.
(using translation)
🎉 This is my first pull request!
=> feat: Add clear() to useSet

docs/useStateList.md, src/useStateList.ts, stories/useStateList.story.tsx, tests/useStateList.test.ts
I wanted to directly add `isFirst` and `isLast` to the return props. This way, I won't need to use `currentIndex == array.length`, and I'll have them available directly in the return state props.
- [/] Comment the code, particularly in hard-to-understand areas
=> feat(pencil): add isFirst and isLast return value to 'useStateList'

docs/useWindowSize.md, src/useWindowSize.ts, stories/useWindowSize.story.tsx, tests/useWindowSize.test.tsx
This update adds an `onChange` callback to the `useWindowSize` hook, allowing custom logic to be executed on window resize. It also integrates `@storybook/addon-actions` to log resize events in Storybook's "Actions" panel.
=> feat: add onChange callback to useWindowSize (#915)
