streamich/react-use

src/useToggle.ts

BREAKING CHANGE: now useToggle and useBoolean accept any value type and cast it to
boolean.

feat: 🎸 accept any value type in useToggle and cast it to bool

---

README.md
docs/useLocalStorage.md
package.json
src/__stories__/useAdopt.story.tsx
src/__stories__/useLocalStorage.story.tsx
src/react.ts
src/useLocalStorage.ts
yarn.lock

Local storage

---

docs/useSpring.md

Hey,
Noticed a typo so have gone ahead and fixed it.

Fixed typo in useSpring.md

---

docs/useSetState.md
src/__stories__/useSetState.story.tsx
src/react.ts
src/useSetState.ts

As `setState` in class component can accept function as argument, we should support it either.

make setState of useSetState accept function argument

---

README.md
docs/useSessionStorage.md
src/__stories__/useSessionStorage.story.tsx
src/index.ts
src/useSessionStorage.ts

Add useSessionStorage

---

README.md
docs/useWait.md
package-lock.json
package.json
src/__stories__/useWait.story.tsx
src/index.ts
src/useWait.ts

Added useWait Hook that manages multiple waiting states.
Complete documentation: https://github.com/f/use-wait
Here's the story:
```jsx
import * as React from 'react';
import {storiesOf} from '@storybook/react';
import {useWait} from '..';
import ShowDocs from '../util/ShowDocs';
const AnotherComponent = () => {
const { isWaiting } = useWait();
return <p>
{ isWaiting('creating user') ? "Now creating user..." : "" }
</p>
}
const Demo = () => {
const { Wait, isWaiting, startWaiting, endWaiting } = useWait();
function createUser() {
startWaiting('creating user');
setTimeout(() => {
endWaiting('creating user');
}, 1000)
}
return (
<div>
<button disabled={isWaiting('creating user')} onClick={createUser}>
<Wait message="creating user" waiting={<b>Creating User...</b>}>
Create User
</Wait> …
```

add useWait Hook

---

docs/useWait.md
package.json
src/__stories__/useWait.story.tsx
src/useWait.ts

npm gave me the name react-wait (thanks to them) and I changed the name. Also updated the version with improvements.

Renamed package from use-wait to react-wait

---

README.md
docs/useDebounce.md
src/__stories__/useDebounce.story.tsx
src/index.ts
src/useDebounce.ts

React hook that delays invoking a function until after wait milliseconds have elapsed since the last time the debounced function was invoked.

feat: added useDebounce hook

---

src/useDebounce.ts
src/useToggle.ts

useToggle and useDebounce cause unnecessary rerenders.
I fixed that. 😄

rerender optimizations for useToggle and useDebounce

---

src/useGeolocation.ts

just add error state to useGeolocation.
in case if the user blocks geolocation message.

add error state to useGeolocation state

---

src/useKeyPress.ts

fix: 🐛 better async loading for keyboardjs

---

docs/createMemo.md
src/__stories__/createMemo.story.tsx

```js
const fibonacci = n => {
if (n === 0) return 0;
if (n === 1) return 1;
return fibonacci(n - 1) + fibonacci(n - 2);
};
```

fix: correct createMemo.story

---

tsconfig.json

- https://github.com/streamich/react-use/issues/140

feat: transpile down to ES5

---

README.md
docs/useWindowScroll.md
src/__stories__/useWindowScroll.story.tsx
src/index.ts
src/useWindowScroll.ts

Created a window scroll hook, can also create a scroll hook for HTML element refs if this one is good. Related to #45

useWindowScroll hook

---

README.md
docs/useScroll.md
docs/useWindowScroll.md
src/__stories__/useScroll.story.tsx
src/__stories__/useWindowScroll.story.tsx
src/index.ts
src/useScroll.ts

Added scroll hook for DOM elements, related to #45

useScroll hook

---

README.md
docs/useLockBodyScroll.md
src/__stories__/useLockBodyScroll.story.tsx
src/index.ts
src/useLockBodyScroll.ts

Based on https://usehooks.com/useLockBodyScroll/ but added a `enabled` parameter so you can disable the lock on scrolling with a state toggle

useLockBodyScroll

---

package.json

Huge apology!
Forgot to update `"module"` field in package.json

fix: set 'module' field properly

---

src/useAsync.ts

did the same thing again as    https://github.com/streamich/react-use/pull/80/commits/7c1b107eb463c04f76548644623015e436cf16d5

fix: add optional attributes in AsyncState

---

README.md
docs/useAsyncCallback.md
src/__stories__/useAsyncCallback.story.tsx
src/index.ts
src/useAsyncCallback.ts

`useAsync` with a callback
Alternative names: useAsyncManual, useAsyncCall, useAsyncFn

useAsyncCallback

---

README.md

fix link to useDeepCompareEffect in docs

docs: fix useDeepCompareEffect link

---

src/__stories__/useIdle.story.tsx
src/useIdle.ts

fix(useIdle): include 'ms' prop in uesEffect dependencies

---

docs/useRefMounted.md

Fix example

---

src/createMemo.ts

feat: add type define for createMemo

---

src/createReducer.ts

fixed the #255 async issue,  related to #164 issue.
use `useRef` as state getter and setter ,  `useState` to trigger component render 
I tested it, the log output is same as use redux middleware

enhance #164  createReducer

---

package.json

To make tree-shakeable by webpack.
Closes #324

Add sideEffects false to package.json

---

docs/useMouse.md

Hello good people of react-use,
This PR contains some documentation fixes.

fix(docs): syntax error, improve examples

---

src/useList.ts

Avoid referencing closure variables

fix: use correct list variable in useList

---

src/useLocalStorage.ts

Fix useLocalStorage types for functional updates

---

README.md
docs/usePermission.md
src/__stories__/usePermission.story.tsx
src/index.ts
src/usePermission.ts

feat: add usePermission

---

docs/createReducer.md
src/createReducer.ts

- make docs for `createReducer ` identical to story
- fix `dispatch` creation on every render see [demo](https://codesandbox.io/s/react-use-createreducer-bug-o0po8)

fix: createReducer

---

docs/useAsync.md
src/__stories__/useAsync.story.tsx

useAsync examples with deps

---

docs/useMedia.md
src/useMedia.ts

Isomorphic useMedia

---

docs/useInterval.md
src/__stories__/useInterval.story.tsx
src/index.ts
src/useDebounce.ts
src/useInterval.ts

Add useInterval hook and fix useDebounce hook's bug

---

package.json
src/index.ts
src/useWait.ts
yarn.lock

Add dependency "@types/react-wait"

---

README.md
docs/useDefault.md
src/__stories__/useDefault.story.tsx
src/__tests__/useDefault.test.tsx
src/index.ts
src/useDefault.ts

Returns default value when state is null or undefined

useDefault hook

---

src/index.ts

Made it way simpler and shorter by replacing imports with re-exports.
Thus it become twice shorter and easier to make changes.

Simplified index.ts file

---

docs/useKeyboardJs.md
src/__stories__/useKeyboardJs.story.tsx
src/useKeyboardJs.ts

fix(useKeyboardJs): fix argument type error

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

it would be way better if all issues will be standardised.

chore: add GitHub issue templates

---

src/useUpdateEffect.ts

fix: #513
when the useEffect function change , useEffect will run again，same to deps change~

fix: useUpdateEffect run on the wrong time

---

src/useCopyToClipboard.ts
src/useDeepCompareEffect.ts
tsconfig.json

fix: https://github.com/streamich/react-use/issues/531

fix: rollup build error: Cannot call a namespace ('writeText')

---

src/useUpdateEffect.ts

fix useUpdateEffect return missing

fix: return from useUpdateEffect

---

docs/useBattery.md
src/__stories__/useBattery.story.tsx
src/useBattery.ts

useBattery now doesn't crashing if used on browsers not supporting `BatteryManager` API';
Fix: #308;

fix: Reworked useBattery hook

---

README.md
docs/useTimeout.md
docs/useTimeoutFn.md
src/__stories__/useTimeout.story.tsx
src/__stories__/useTimeoutFn.story.tsx
src/__tests__/useTimeout.test.ts
src/__tests__/useTimeoutFn.test.ts
src/index.ts
src/useTimeout.ts
src/useTimeoutFn.ts

useTimeout:
- added cancel method;
- added reset method;
- improved docs;
- added tests;

feat: useTimeout add cancel and reset handles

---

.editorconfig
src/__stories__/useGetSetState.story.tsx
src/__stories__/useLogger.story.tsx
src/__stories__/useRafLoop.story.tsx
src/__stories__/useUpsert.story.tsx
src/__tests__/createReducer.test.ts
src/__tests__/useNumber.test.ts
src/__tests__/useObservable.test.ts
src/__tests__/useRaf.test.ts
src/__tests__/useSpring.test.ts
src/__tests__/useTween.test.ts
src/useEvent.ts
src/useInterval.ts
src/useKey.ts
src/useMountedState.ts
src/useSetState.ts
src/useSize.tsx
src/useSpring.ts
tslint.json

- All files in src dir been fixed;
- .editorconfig:
- Force if-else braces placement;
- typescript rules separated from others;
- more alignment rules.
- tslint:
- Allow leading underscore.

Improved editorconfig

---

docs/useLockBodyScroll.md
package.json
src/__stories__/useLockBodyScroll.story.tsx
src/useLockBodyScroll.ts
yarn.lock

Fix: #550, now it supports iframes.
Sadly to test it we should use karma as a tests runner, but it is incompatible with jest, so - no tests coverage for now.

fix: make useLockBodyScroll support iframes

---

docs/createReducer.md

Incrementing will give NaN
CodeSandbox: https://codesandbox.io/s/condescending-bohr-9xe85

fix: update createReducer to fix initial state

---

src/__tests__/useInterval.test.ts

Add tests for useInterval hook. No issues found.

Add tests for useInterval hook

---

docs/useTimeoutFn.md
src/__tests__/useTimeoutFn.test.ts
src/useTimeoutFn.ts

- reset function should clear previous timeout;
- function change should not reset the timeout;

fix: make useTimeoutFn work properly:

---

src/__tests__/useUpdate.test.ts
src/useUpdate.ts

This fix https://github.com/streamich/react-use/issues/463

Fix useUpdate returned callback

---

docs/useAudio.md
docs/useVideo.md
src/__tests__/useAudio.test.ts
src/util/createHTMLMediaHook.ts

According to this issue https://github.com/streamich/react-use/issues/284 , change from `isPlaying` to precise property name `paused`.

Using paused property instead of isPlaying

---

.circleci/config.yml
README.md
docs/useSearchParam.md
src/__stories__/useSearchParam.story.tsx
src/__tests__/useSearchParam.test.ts
src/index.ts
src/useSearchParam.ts

useSearchParam

---

README.md

Added a demo link for `useStateList`

improve docs: useStateList demo link

---

README.md
docs/usePrevious.md

Added a demo link for `usePrevious` and improved example.

improve docs: usePrevious demo link

---

README.md
docs/useToggle.md

Added a demo link for `useToggle`

improve docs: useToggle demo link

---

README.md
docs/useMap.md
src/__stories__/useMap.story.tsx

Added a demo link for `useMap`

improve docs: useMap demo link

---

README.md
docs/useList.md
src/__stories__/useList.story.tsx

Added a demo link for `useList`

improve docs: useList demo link

---

docs/useInterval.md
src/__stories__/useInterval.story.tsx
src/useInterval.ts

Renamed callback ref variable and improved documentation example on how to pause the interval.

useInterval refactor and docs

---

docs/useMount.md
docs/useUnmount.md
src/__stories__/useMount.story.tsx
src/__stories__/useUnmount.story.tsx
src/__stories__/util/ActionsTabStory.tsx

ActionsTabStory.tsx instead ConsoleStory.tsx

Added ActionsTabStory for log

---

README.md
src/index.ts
src/useWait.ts

Should be merged before #711 and published as patch version;

feat(useWait): add deprecation messages to readme and export;

---

src/__tests__/useTitle.test.tsx
src/useTitle.ts

Previous implementation been using `useEffect` cook that made it async, now hook is sinchronous and possible to test.
Due to new react's concurrent mode it's better to make separate hooks as more synchronous as possible.

feat(useTitle): hook rework

---

src/__tests__/usePreviousDistinct.test.tsx
src/createReducer.ts
src/usePreviousDistinct.ts
src/util/parseTimeRanges.ts

1) Reworked tests so they're passing on recent ts and testing library versions.
2) Reworked a bit a hook behavior and improved types:
Now predicate function will NOT be called on intial render because there is no ibvious sense to compare initial value with itself.

feat(usePreviousDistinct): fix tests and improve the hook

---

src/__tests__/useWindowSize.test.tsx
src/createReducer.ts
src/useWindowSize.ts
src/util/parseTimeRanges.ts

A bit changed lyfecycle no need to return anything @ server side and added types;
Rewritten tests - covers more cases and will work on next @testing-library/react-hooks release (been broken before);

feat(useWindowSize): rewritten tests to prepare to @testing-library/react-hooks release v3

---

src/useTitle.ts

Now for SSR and all other cases when `document` is missing hook is stubbed with noop function.

fix(#749): now should work with SSR

---

README.md
docs/useVibrate.md
src/__stories__/useVibrate.story.tsx
src/index.ts
src/useVibrate.ts

Implementation of a vibration effect hook that can be controlled with an `enabled` parameter. Will add tests if we like the hook signature of this proposal. Generally only works on Android phones...
Closes #43

useVibrate

---

README.md
docs/useList.md
docs/useUpsert.md
src/__stories__/useList.story.tsx
src/__tests__/useList.test.ts
src/useList.ts
src/useUpsert.ts
src/util/resolveHookState.ts

Brings lots of functionality, also partially implements whats done in #590 
- Now the actions object is persist over renders, so no need to add list to deps when working with list actions;
- Added `insertAt` to insert item in certain index and shift all of rightleft items;
- Added `update` and `updateFirst` methods, they're updating elements that matches passed predicate. `update` updates all of items matching the predicate, `updateFirst` only first item;
- Added `upsert` method - almost like `updateFirst` but this time it will push item to the list in case of predicate miss;
- Existed action `remove` renamed to `removeAt`, due to more intuitive name, although for some time `remove` will persist as a ref to `removeAt`;
- `filter` action now has same signature with native …

feat(useList): reimplemented useList hook;

---

src/useThrottleFn.ts

My proposal for Issue https://github.com/streamich/react-use/issues/764.
**Side note**:  The returned value is `T | null`, `T | undefined` would probably be more accurate and would avoid workaround on line 5 (`useState<T>()` instead of `useState<T | null>(null)`), but I did not implemented it as it would have been a breaking change.

Type use throttle fn

---

README.md
docs/useSet.md
src/__stories__/useSet.story.tsx
src/index.ts
src/useSet.ts
tests/useSet.test.ts

feat: Add useSet hook

---

src/__stories__/useMultiStateValidator.story.tsx
src/__stories__/useStateValidator.story.tsx
src/useMultiStateValidator.ts
src/useStateValidator.ts
tests/useMultiStateValidator.test.ts
tests/useStateValidator.test.ts

feat(useStateValidator): Refactor method and improve typings;
feat(useMultiStateValidator): Refactor method and improve typings;

feat: Improve useStateValidator & useMultiStateValidator typings

---

docs/useQueue.md
src/__stories__/useQueue.story.tsx

Fix spelling of remove in useQueue story and change usage of pop to remove in .md file

fix spelling in useQueue doc and story

---

README.md

* fixed `createBreakpoint` link in README

chore: fixes createBreakpoint link

---

package.json
tests/useAsyncFn.test.tsx
tests/useEnsuredForwardedRef.test.tsx
tests/useIntersection.test.tsx
tests/usePreviousDistinct.test.tsx
tests/useWindowSize.test.tsx

TSX specs were ignored from `yarn test`

fix: TSX specs were ignored from `yarn test`

---

src/useMap.ts
tests/useMap.test.ts

fix: "get" method in useMap updated to reference latest map object

---

docs/useList.md

Typo in useList md

---

src/useSet.ts

Fixes: https://github.com/streamich/react-use/issues/808

fix: use latest set object in useSet "has" method

---

src/useUpdate.ts

if we using reducer instead of useState then we don't need a useCallback and it's performance will increase

change useUpdate hook to use `reducer` instead of `state + callback`

---

tests/useAsync.test.tsx

Fix act warning in useAsync tests

---

README.md
package.json

1. #892 
2. Add missing link for `useCookie` in Readme

fix: update the types dependency for js-cookie

---

src/useLockBodyScroll.ts

This gets the absolute minimum working, but I want to get feedback before continuing. I'll also annotate the code for changes

[WIP] Lock iOS Body on click

---

docs/useLocalStorage.md
package.json
src/useLocalStorage.ts
tests/setupTests.ts
tests/useLocalStorage.test.ts
yarn.lock

1. #834 
2. Add tests for `useLocalStorage` hook

feat: add serializer/deserializer option to useLocalStorage

---

README.md
docs/useError.md
src/index.ts
src/useError.ts
stories/useError.story.tsx
tests/useError.test.ts

feat: add useError hook

---

src/useDefault.ts

Added generic type for `useDefault` state
Typesafe for `useDefault`

feat: Typings for `useDefault`

---

README.md
docs/useLongPress.md
src/index.ts
src/useLongPress.ts
stories/useLongPress.story.tsx
tests/useLongPress.test.tsx

feat: add useLongPress hook

---

docs/useStateList.md

[FIX] typo in useStateList.md

---

docs/useStateWithHistory.md

Fix typos and doc error

---

src/util/createHTMLMediaHook.ts

createHTMLMediaHook is used for audio and video. Error message should reflect which one is created.

Fix error message typo

---

docs/useRafLoop.md
package.json
src/useRafLoop.ts
stories/useRafLoop.story.tsx
tests/useRafLoop.test.tsx

Reworked the hook so it do not causing parent component re-render.
Also closes #1090

feat(useRafLoop): rework the hook

---

README.md
docs/useHash.md
src/index.ts
src/useHash.ts
stories/useHash.story.tsx
tests/useHash.test.ts

`const [hash, setHash] = useHash()`
get/set url hash value.
- `hash: string`: get current url hash. listen to `hashchange` event.
- `setHash: (newHash: string) => void`: change url hash. Invoke this method will trigger `hashchange` event similar to assign value to `window.location.hash`.
```jsx
import {useHash} from 'react-use';
const Demo = () => {
const [hash, setHash] = useHash();
useMount(() => {
setHash('#/path/to/page?userId=123');
});
return (
<div>
<div>window.location.href:</div>
<div>
<pre>{window.location.href}</pre>
</div>
<div>Edit hash: </div>
<div>
<input style={{ width: '100%' }} value={hash} onChange={e => setHash(e.target.value)} />
</div>
</div>
);
};
```

feat: add useHash hook

---

src/useSlider.ts
stories/useSlider.story.tsx

Provides value where scrub stopped in `onScrubStop` prop in `useSlider` hook.

feat: 🎸 onScrubStop provide value where scrub stopped

---

README.md
docs/useScratch.md
package.json
src/index.ts
src/useScratch.ts
stories/useScratch.story.tsx
yarn.lock

Use scratch 4

---

docs/useMeasure.md
src/useMeasure.ts
tests/setupTests.ts
tests/useMeasure.test.ts

Improvements to `useMeasure` hook.

Improve use measure

---

README.md
docs/useMouseWheel.md
src/index.ts
src/useMouseWheel.ts
stories/useMouseWheel.story.tsx

add useMouseWheel hook to get deltaY of scrolled mouse wheel.

feat: add useMouseWheel hook

---

src/useLockBodyScroll.ts

As described in https://github.com/streamich/react-use/issues/858 the ```useLockBodyScroll``` hook, is not unlocking the body on unmount.
Fix: Added an effect for observing component unmount. This effect will unlock the body when the component is unmounted. Also due to the changes, there was duplicate code for unlocking functionality. So I have separated the **lock** and **unlock** functionalities into methods so that it can be reused.

fix:  doesn't unlock the body on unmount

---

tests/useDebounce.test.ts

The test description was wrong - the hook returns two functions.

chore(useDebounce): fix test description

---

package.json

Update react, react-dom to v17.0.1

---

src/useMultiStateValidator.ts
src/useStateValidator.ts

Now it is compatible with TS 4.x.x

fix: improve useStateValidator and useMultiStateValidator typings.

---

src/misc/util.ts

feat: improve `on` and `off` util functions typing.

---

jest.config.base.ts
jest.config.node.ts
jest.config.ts
package.json
src/misc/util.ts
src/useBattery.ts
src/useIsomorphicLayoutEffect.ts
src/useMediaDevices.ts
src/useNetworkState.ts
src/useVibrate.ts
tests/setupTests.ts
tsconfig.json

should fix: #1777
Also introduce jest config for ssr tests (it fails hard now).

fix: proper definition for isBrowser and isNavigator states.

---

package.json
yarn.lock

As per https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies.
Fixes #892.

Move @types/js-cookie to dependencies

---

src/useMeasureDirty.ts

fix: memory leak in useMeasureDirty

---

src/useEvent.ts
src/useKey.ts

Just completed useKey arguments type

fix useKey type problem

---

src/usePermission.ts
src/useSpeech.ts
stories/useSpeech.story.tsx

refactor: (useSpeech,usePermission) improved types

---

.github/workflows/pull_request_ci.yml

ci: 🎡 bump github actions node version

---

src/useSessionStorage.ts

Just fixing a small typo :smile:

Fix typo in useSessionStorage.ts

---

package.json
yarn.lock

https://github.com/streamich/react-use/issues/2319

fix: Official site build file error

---

package.json

When installing `react-use` in a project with react 18 you might see the errors:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myproject@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   dev react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0  || ^17.0.0" from react-use@17.3.2
npm ERR! node_modules/react-use
npm ERR!   dev react-use@"^17.3.2" from the root project
```
Workaround is using `npm install --force`

chore(deps): update peerDependencies for react 18

---

README.md
docs/usePinchZoom.md
src/index.ts
src/usePinchZoom.ts
stories/usePinchZoom.story.tsx

Proposal - add usePinchZoom sensor hook

---

docs/usePinchZoom.md

Fix typo in usePinchZoom.md
- [v] Read the [Contributing Guide](https://github.com/streamich/react-use/blob/master/CONTRIBUTING.md)
- [v] Perform a code self-review
- [v] Comment the code, particularly in hard-to-understand areas
- [v] Add documentation
- [v] Add hook's story at Storybook
- [v] Cover changes with tests
- [v] Ensure the test suite passes (`yarn test`)
- [v] Provide 100% tests coverage
- [v] Make sure code lints (`yarn lint`). Fix it with `yarn lint:fix` in case of failure.
- [v] Make sure types are fine (`yarn lint:types`).

docs: fix typo in usePinchZoom

---

docs/useSlider.md

Fixes possible typo in example
